### PR TITLE
Update rubocop to version 0.30.0 & fix offenses.

### LINKED ISSUE #800: Update rubocop gem to 0.30.0
Upgrading to rubocop 0.30.0 includes the following offenses:

```
app/controllers/status_controller.rb:6:36: C: Do not use Time.[:now] without zone. Use #Time.zone.[:now] instead.
    response_hash[:updated] = Time.now.to_i
                                   ^^^
app/helpers/phone_format_helper.rb:37:12: C: Use find instead of select.first.
    phones.select { |phone| voice_or_hotline?(phone) }.first
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
config/environments/production.rb:49:12: C: Use %r around regular expression.
      r301(/\/organizations(.*)/, '/locations$1')
           ^^^^^^^^^^^^^^^^^^^^^
```

### PR DESCRIPTION
**Pull request by monfresh**
Closes #800.

### CODE REVIEW

File: app/helpers/phone_format_helper.rb [hunk 1]
```diff
@@ -34,7 +34,7 @@ def phone_microdata_for(type)
   # @return [String] The first voice or hotline phone number
   #   or nil if none are found.
   def first_voice_or_hotline_phone_for(phones)
-    phones.select { |phone| voice_or_hotline?(phone) }.first
+    phones.find { |phone| voice_or_hotline?(phone) }
```
Comment (monfresh) [inline app/helpers/phone_format_helper.rb]: I don't have a strong preference either way, but I think `find` sounds better, and it's shorter. It's also the default Rubocop preference, so I think we'll go with that. I'll update our Hound config.
